"""
This file contains the dictionaries and lists to randomly create data for our
database. This file is imported into the main file to create the data.
"""

cities = {1: {'city_name': 'New York', 'state_name': 'New York', 'country_name': 'United States'},
            2: {'city_name': 'Los Angeles', 'state_name': 'California', 'country_name': 'United States'},
            3: {'city_name': 'Chicago', 'state_name': 'Illinois', 'country_name': 'United States'},
            4: {'city_name': 'Houston', 'state_name': 'Texas', 'country_name': 'United States'},
            5: {'city_name': 'Austin', 'state_name': 'Texas', 'country_name': 'United States'},
            6: {'city_name': 'San Francisco', 'state_name': 'California', 'country_name': 'United States'},
            7: {'city_name': 'Seattle', 'state_name': 'Washington', 'country_name': 'United States'},
            8: {'city_name': 'Boston', 'state_name': 'Massachusetts','country_name': 'United States'},
            9: {'city_name': 'Toronto', 'country_name': 'Canada'},
            10: {'city_name': 'Montreal', 'country_name': 'Canada'},
            11: {'city_name': 'Vancouver', 'country_name': 'Canada'},
            12: {'city_name': 'Calgary', 'country_name': 'Canada'},
            13: {'city_name': 'Edmonton', 'country_name': 'Canada'},
            14: {'city_name': 'Ottawa', 'country_name': 'Canada'},
            15: {'city_name': 'Winnipeg', 'country_name': 'Canada'},
            16: {'city_name': 'Quebec City', 'country_name': 'Canada'},
            17: {'city_name': 'Hamilton', 'country_name': 'Canada'},
            18: {'city_name': 'London', 'country_name': 'Canada'},
            19: {'city_name': 'Madrid', 'country_name': 'Spain'},
            20: {'city_name': 'Barcelona', 'country_name': 'Spain'},
            21: {'city_name': 'Valencia', 'country_name': 'Spain'},
            22: {'city_name': 'Seville', 'country_name': 'Spain'},
            23: {'city_name': 'Zaragoza', 'country_name': 'Spain'},
            24: {'city_name': 'Málaga', 'country_name': 'Spain'},
            25: {'city_name': 'Murcia', 'country_name': 'Spain'},
            26: {'city_name': 'Palma', 'country_name': 'Spain'},
            27: {'city_name': 'Las Palmas', 'country_name': 'Spain'},
            28: {'city_name': 'Bilbao', 'country_name': 'Spain'},
            29: {'city_name': 'Paris', 'country_name': 'France'},
            30: {'city_name': 'Marseille', 'country_name': 'France'},
            31: {'city_name': 'Lyon', 'country_name': 'France'},
            32: {'city_name': 'Toulouse', 'country_name': 'France'},
            33: {'city_name': 'Nice', 'country_name': 'France'},
            34: {'city_name': 'Nantes', 'country_name': 'France'},
            35: {'city_name': 'Strasbourg', 'country_name': 'France'},
            36: {'city_name': 'Montpellier', 'country_name': 'France'},
            37: {'city_name': 'Bordeaux', 'country_name': 'France'},
            38: {'city_name': 'Lille', 'country_name': 'France'},
            39: {'city_name': 'Berlin', 'country_name': 'Germany'},
            40: {'city_name': 'Hamburg', 'country_name': 'Germany'},
            41: {'city_name': 'Munich', 'country_name': 'Germany'},
            42: {'city_name': 'Cologne', 'country_name': 'Germany'},
            43: {'city_name': 'Frankfurt', 'country_name': 'Germany'},
            44: {'city_name': 'Stuttgart', 'country_name': 'Germany'},
            45: {'city_name': 'Düsseldorf', 'country_name': 'Germany'},
            46: {'city_name': 'Dortmund', 'country_name': 'Germany'},
            47: {'city_name': 'Essen', 'country_name': 'Germany'},
            48: {'city_name': 'Leipzig', 'country_name': 'Germany'},
            49: {'city_name': 'Rome', 'country_name': 'Italy'},
            50: {'city_name': 'Milan', 'country_name': 'Italy'},
            51: {'city_name': 'Naples', 'country_name': 'Italy'},
            52: {'city_name': 'Turin', 'country_name': 'Italy'},
            53: {'city_name': 'Palermo', 'country_name': 'Italy'},
            54: {'city_name': 'Genoa', 'country_name': 'Italy'},
            55: {'city_name': 'Bologna', 'country_name': 'Italy'},
            56: {'city_name': 'Florence', 'country_name': 'Italy'},
            57: {'city_name': 'Bari', 'country_name': 'Italy'},
            58: {'city_name': 'Catania', 'country_name': 'Italy'},
            59: {'city_name': 'London', 'country_name': 'United Kingdom'},
            60: {'city_name': 'Birmingham', 'country_name': 'United Kingdom'},
            61: {'city_name': 'Glasgow', 'country_name': 'United Kingdom'},
            62: {'city_name': 'Liverpool', 'country_name': 'United Kingdom'},
            63: {'city_name': 'Bristol', 'country_name': 'United Kingdom'},
            64: {'city_name': 'Manchester', 'country_name': 'United Kingdom'},
            65: {'city_name': 'Sheffield', 'country_name': 'United Kingdom'},
            66: {'city_name': 'Leeds', 'country_name': 'United Kingdom'},
            67: {'city_name': 'Edinburgh', 'country_name': 'United Kingdom'},
            68: {'city_name': 'Leicester', 'country_name': 'United Kingdom'},
            69: {'city_name': 'Shanghai', 'country_name': 'China'},
            70: {'city_name': 'Beijing', 'country_name': 'China'},
            71: {'city_name': 'Tianjin', 'country_name': 'China'},
            72: {'city_name': 'Guangzhou', 'country_name': 'China'},
            73: {'city_name': 'Shenzhen', 'country_name': 'China'},
            74: {'city_name': 'Wuhan', 'country_name': 'China'},
            75: {'city_name': 'Dongguan', 'country_name': 'China'},
            76: {'city_name': 'Chongqing', 'country_name': 'China'},
            77: {'city_name': 'Chengdu', 'country_name': 'China'},
            78: {'city_name': 'Nanjing', 'country_name': 'China'},
            79: {'city_name': 'Tokyo', 'country_name': 'Japan'},
            80: {'city_name': 'Yokohama', 'country_name': 'Japan'},
            81: {'city_name': 'Osaka', 'country_name': 'Japan'},
            82: {'city_name': 'Nagoya', 'country_name': 'Japan'},
            83: {'city_name': 'Sapporo', 'country_name': 'Japan'},
            84: {'city_name': 'Fukuoka', 'country_name': 'Japan'},
            85: {'city_name': 'Kobe', 'country_name': 'Japan'},
            86: {'city_name': 'Kyoto', 'country_name': 'Japan'},
            87: {'city_name': 'Kawasaki', 'country_name': 'Japan'},
            88: {'city_name': 'Saitama', 'country_name': 'Japan'},
            89: {'city_name': 'Mexico City', 'country_name': 'Mexico'},
            90: {'city_name': 'Ecatepec', 'country_name': 'Mexico'},
            91: {'city_name': 'Guadalajara', 'country_name': 'Mexico'},
            92: {'city_name': 'Puebla', 'country_name': 'Mexico'},
            93: {'city_name': 'Juárez', 'country_name': 'Mexico'},
            94: {'city_name': 'Tijuana', 'country_name': 'Mexico'},
            95: {'city_name': 'León', 'country_name': 'Mexico'},
            96: {'city_name': 'Zapopan', 'country_name': 'Mexico'},
            97: {'city_name': 'Monterrey', 'country_name': 'Mexico'},
            98: {'city_name': 'Nezahualcóyotl', 'country_name': 'Mexico'},
            99: {'city_name': 'São Paulo', 'country_name': 'Brazil'},
            100: {'city_name': 'Rio de Janeiro', 'country_name': 'Brazil'},
            101: {'city_name': 'Salvador', 'country_name': 'Brazil'},
            102: {'city_name': 'Brasília', 'country_name': 'Brazil'},
            103: {'city_name': 'Fortaleza', 'country_name': 'Brazil'},
            104: {'city_name': 'Belo Horizonte', 'country_name': 'Brazil'},
            105: {'city_name': 'Manaus', 'country_name': 'Brazil'},
            106: {'city_name': 'Curitiba', 'country_name': 'Brazil'},
            107: {'city_name': 'Recife', 'country_name': 'Brazil'},
            108: {'city_name': 'Porto Alegre', 'country_name': 'Brazil'},
            109: {'city_name': 'Seoul', 'country_name': 'Korea'},
            110: {'city_name': 'Busan', 'country_name': 'Korea'},
            111: {'city_name': 'Incheon', 'country_name': 'Korea'},
            112: {'city_name': 'Daegu', 'country_name': 'Korea'},
            113: {'city_name': 'Daejeon', 'country_name': 'Korea'},
            114: {'city_name': 'Gwangju', 'country_name': 'Korea'},
            115: {'city_name': 'Ulsan', 'country_name': 'Korea'},
            116: {'city_name': 'Suwon', 'country_name': 'Korea'},
            117: {'city_name': 'Changwon', 'country_name': 'Korea'},
            118: {'city_name': 'Seongnam', 'country_name': 'Korea'}}

first_names = ['Ryan', 'Charlie', 'Sebastian', 'CJ', 'Will', 'Eddie', 'Matthew', 'Nathan', 'Ben', 'Ethan', 'Liam',
               'Mason', 'Noah', 'Oliver', 'Jacob', 'Lucas', 'Michael', 'Alexander', 'Daniel', 'James', 'Henry', 'David',
               'Joseph', 'Samuel', 'Jack', 'John', 'Luke', 'Oscar', 'Max', 'Leo', 'Levi', 'Eli', 'Ezra', 'Isaac', 'Caleb',
               'Wyatt', 'Hunter', 'Jaxon', 'Julian', 'Adrian', 'Robert', 'Charles', 'Thomas', 'Nolan', 'Dylan', 'George',
               'Adam', 'Zachary', 'Tyler', 'Evan', 'Colton', 'Jace', 'Miles', 'Bennett', 'Harrison', 'Jordan', 'Austin',
               'Gavin', 'Parker', 'Cooper', 'Chase', 'Tristan', 'Jason', 'Xavier', 'Josiah', 'Brody', 'Asher', 'Nathaniel',
               'Ryder', 'Justin', 'Bryce', 'Camden', 'Jaden', 'Micah', 'Kai', 'Landon', 'Zane', 'Blake', 'Brayden',
               'Emmett', 'Caden', 'Carter', 'Vincent', 'Maverick', 'Edward', 'Dominic', 'Paxton', 'Greyson', 'Ian',
               'Easton', 'Kingston', 'Olivia', 'Emma', 'Ava', 'Sophia', 'Isabella', 'Mia', 'Charlotte', 'Abigail', 'Emily',
               'Megan', 'Linda', 'Gracie', 'Hannah', 'Madison', 'Bella', 'Chloe', 'Elizabeth', 'Ella', 'Scarlett', 'Lily',
               'Avery', 'Addison', 'Aubrey', 'Layla', 'Natalie', 'Zoey', 'Sofia', 'Grace', 'Victoria', 'Camila', 'Penelope',
               'Riley', 'Lillian', 'Nora', 'Zoe', 'Leah', 'Hazel', 'Violet', 'Aurora', 'Savannah', 'Audrey', 'Brooklyn',
               'Bella', 'Claire', 'Skylar', 'Ellie', 'Samantha', 'Stella', 'Paisley', 'Everly', 'Nova', 'Emilia', 'Aria',]

last_names = ['Wong', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez',
              'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
              'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker',
              'Young', 'Hall', 'Allen', 'Torres', 'Nguyen', 'Wright', 'Flores', 'King', 'Scott', 'Rivera', 'Green', 'Hill',
              'Adams', 'Baker', 'Nelson', 'Mitchell', 'Campbell', 'Gomez', 'Carter', 'Roberts', 'Diaz', 'Phillips', 'Evans',
              'Turner', 'Reyes', 'Cruz', 'Parker', 'Edwards', 'Collins', 'Stewart', 'Morris', 'Morales', 'Murphy', 'Cook',
              'Rogers', 'Gutierrez', 'Ortiz', 'Morgan', 'Cooper', 'Peterson', 'Bailey', 'Reed', 'Kelly', 'Howard', 'Ramos',
              'Kim', 'Cox', 'Ward', 'Richardson', 'Watson', 'Brooks', 'Chavez', 'Wood', 'James', 'Bennett', 'Gray', 'Mendoza',
              'Li', 'Reyes', 'Lynch', 'Huang', 'Murray', 'Graham', 'Sullivan', 'Wallace', 'Woods', 'Cole', 'West', 'Jordan', 'Speer']

adjectives = ['awesome', 'fun', 'exciting', 'cool', 'beautiful', 'interesting', 'amazing', 'enjoyable', 'wonderful',
              'fantastic', 'delightful', 'pleasant', 'excellent', 'great', 'terrific', 'superb', 'marvelous', 'fabulous',
              'lovely', 'magnificent', 'splendid', 'glorious', 'stunning', 'breathtaking', 'spectacular', 'remarkable',
              'extraordinary', 'incredible', 'unforgettable', 'memorable', 'unbelievable', 'astonishing', 'phenomenal',
              'mind-blowing', 'jaw-dropping', 'eye-opening', 'mind-bending', 'mind-boggling']



